import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "../components/_components/Header"
import Footer from "../components/_components/Footer"
import {Toaster} from "../components/ui/toaster"
const outfit = Outfit({
  
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className}  antialiased`}
      >
        <div className="md:px-20">
          <Header/>
          {children}
          <Footer/>
          <Toaster />
          </div>
        </body>
      </html>
  );
}
